config/routes.rb
Rails.application.routes.draw do
  get :search, 'search/index'
  root 'static_pages#home'
  resources :atheletes
  resources :championships
  resources :skills
  resources :atheletes_championships
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/championship.rb
class Championship < ApplicationRecord
    has_and_belongs_to_many :atheletes, through: :athelete_championship
end

app/controllers/championships_controller.rb
class ChampionshipsController < ApplicationController
  before_action :set_championship, only: [:show, :edit, :update, :destroy]

  # GET /championships
  # GET /championships.json
  def index
    @championships = Championship.all
  end

  # GET /championships/1
  # GET /championships/1.json
  def show
  end

  # GET /championships/new
  def new
    @championship = Championship.new
  end

  # GET /championships/1/edit
  def edit
  end

  # POST /championships
  # POST /championships.json
  def create
    @championship = Championship.new(championship_params)

    respond_to do |format|
      if @championship.save
        format.html { redirect_to @championship, notice: 'Championship was successfully created.' }
        format.json { render :show, status: :created, location: @championship }
      else
        format.html { render :new }
        format.json { render json: @championship.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /championships/1
  # PATCH/PUT /championships/1.json
  def update
    respond_to do |format|
      if @championship.update(championship_params)
        format.html { redirect_to @championship, notice: 'Championship was successfully updated.' }
        format.json { render :show, status: :ok, location: @championship }
      else
        format.html { render :edit }
        format.json { render json: @championship.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /championships/1
  # DELETE /championships/1.json
  def destroy
    @championship.destroy
    respond_to do |format|
      format.html { redirect_to championships_url, notice: 'Championship was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_championship
      @championship = Championship.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def championship_params
      params.require(:championship).permit(:name, :grant_date)
    end
end

app/helpers/championships_helper.rb
module ChampionshipsHelper
end

app/views/championships/_form.html.erb
<%= form_with(model: championship, local: true) do |form| %>
  <% if championship.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(championship.errors.count, "error") %> prohibited this championship from being saved:</h2>

      <ul>
        <% championship.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>
  
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/championships/edit.html.erb
<h1>Editing Championship</h1>

<%= render 'form', championship: @championship %>

<%= link_to 'Show', @championship %> |
<%= link_to 'Back', championships_path %>

app/views/championships/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Championships</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @championships.each do |championship| %>
      <tr>
        <td><%= championship.name %></td>
        <td><%= link_to 'Show', championship %></td>
        <td><%= link_to 'Edit', edit_championship_path(championship) %></td>
        <td><%= link_to 'Destroy', championship, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Championship', new_championship_path %>

app/views/championships/new.html.erb
<h1>New Championship</h1>

<%= render 'form', championship: @championship %>

<%= link_to 'Back', championships_path %>

app/views/championships/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @championship.name %>
</p>

<%= link_to 'Edit', edit_championship_path(@championship) %> |
<%= link_to 'Back', championships_path %>