config/routes.rb
Rails.application.routes.draw do
  get :search, 'search/index'
  root 'static_pages#home'
  resources :atheletes
  resources :championships
  resources :skills
  resources :atheletes_championships
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/skill.rb
class Skill < ApplicationRecord
  belongs_to :parent, class_name: 'Skill', optional: true
  has_many :children, class_name: 'Skill', foreign_key: 'parent_id'
  has_and_belongs_to_many :atheletes, through: :athelete_skill
  
  MAX_DEPTH = 5

  def name_short 
    name
  end

  def self.search_by_name(name)
      if name 
          where(["lower(name) LIKE ?","%#{name.downcase}%"])
      else
          all
      end
  end

  def self.extend_skills_to_children(skills)
    extended_skills = []
    skills.each do |skill|
      extended_skills += self.extend_skill_to_children(skill)
    end
    extended_skills.uniq
  end

  private
    def self.extend_skill_to_children(skill, depth = 0)
      return [] if depth > MAX_DEPTH # Prevent Infinite Loops if a bad skill-design was made
      extended_skills = [skill]
      skill_children = skill.children
      if skill_children
        skill_children.each do |child|
          extended_skills += self.extend_skill_to_children(child, depth + 1)
        end
      end
      extended_skills
    end

end

app/controllers/skills_controller.rb
class SkillsController < ApplicationController
  before_action :set_skill, only: [:show, :edit, :update, :destroy]

  # GET /skills
  # GET /skills.json
  def index
    @skills = Skill.all
  end

  # GET /skills/1
  # GET /skills/1.json
  def show
  end

  # GET /skills/new
  def new
    @skill = Skill.new
  end

  # GET /skills/1/edit
  def edit
  end

  # POST /skills
  # POST /skills.json
  def create
    @skill = Skill.new(skill_params)

    respond_to do |format|
      if @skill.save
        format.html { redirect_to @skill, notice: 'Skill was successfully created.' }
        format.json { render :show, status: :created, location: @skill }
      else
        format.html { render :new }
        format.json { render json: @skill.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /skills/1
  # PATCH/PUT /skills/1.json
  def update
    respond_to do |format|
      if @skill.update(skill_params)
        format.html { redirect_to @skill, notice: 'Skill was successfully updated.' }
        format.json { render :show, status: :ok, location: @skill }
      else
        format.html { render :edit }
        format.json { render json: @skill.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /skills/1
  # DELETE /skills/1.json
  def destroy
    @skill.destroy
    respond_to do |format|
      format.html { redirect_to skills_url, notice: 'Skill was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_skill
      @skill = Skill.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def skill_params
      params.require(:skill).permit(:name, :parent_id)
    end
end

app/helpers/skills_helper.rb
module SkillsHelper
end

app/views/skills/_form.html.erb
<%= form_with(model: skill, local: true) do |form| %>
  <% if skill.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(skill.errors.count, "error") %> prohibited this skill from being saved:</h2>

      <ul>
        <% skill.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :parent_id %>
    <%= form.collection_select :parent_id, Skill.order(:name),:id,:name, include_blank: true %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/skills/edit.html.erb
<h1>Editing Skill</h1>

<%= render 'form', skill: @skill %>

<%= link_to 'Show', @skill %> |
<%= link_to 'Back', skills_path %>

app/views/skills/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Skills</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Parent</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @skills.each do |skill| %>
      <tr>
        <td><%= skill.name %></td>
        <td><%= skill.parent ? skill.parent.name : "No Parent" %></td>
        <td><%= link_to 'Show', skill %></td>
        <td><%= link_to 'Edit', edit_skill_path(skill) %></td>
        <td><%= link_to 'Destroy', skill, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Skill', new_skill_path %>

app/views/skills/new.html.erb
<h1>New Skill</h1>

<%= render 'form', skill: @skill %>

<%= link_to 'Back', skills_path %>

app/views/skills/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @skill.name %>
</p>

<p>
  <strong>Parent:</strong>
  <%= @skill.parent ? @skill.parent.name : "No Parent" %>
</p>

<%= link_to 'Edit', edit_skill_path(@skill) %> |
<%= link_to 'Back', skills_path %>