config/routes.rb
Rails.application.routes.draw do
  get :search, 'search/index'
  root 'static_pages#home'
  resources :atheletes
  resources :championships
  resources :skills
  resources :atheletes_championships
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/athelete.rb
class Athelete < ApplicationRecord
    has_and_belongs_to_many :skills, through: :athelete_skill
    has_many :atheletes_championships
    has_and_belongs_to_many :championships, through: :atheletes_championship

    def self.search_by_name(name)
        if name.empty?
            { error: "Empty Search Query" }
        else
            { atheletes: where(["lower(name) LIKE ?","%#{name.downcase}%"]) }
        end
    end

    def self.search_by_skill(skill)
        if skill.empty?
            { error: "Empty Search Query" }
        else
            main_skills = Skill.search_by_name(skill)
            extended_skills = Skill.extend_skills_to_children(main_skills)
            { atheletes: joins(:atheletes_skills).where('atheletes_skills.skill' => extended_skills).uniq, 
              skills: main_skills, extended_skills: extended_skills}
        end
    end

    def self.search_by_age_range(age_range)
        match = age_range.match /^(\d+)\-(\d+)$/ # Age Range
        if match
            age_from = match[1].to_i
            age_to = match[2].to_i
            birthdate_from = (age_to).years.ago
            birthdate_to = (age_from).years.ago
            { atheletes: where(birthdate: birthdate_from..birthdate_to) }
        else
            match = age_range.match /^([><])(\d+)$/ # Comparator and Age
            unless match
                return { error: "Invalid Age Range (correct examples: 2-10, <6, >2)" }
            end
            age = match[2].to_i
            birthdate = (age).years.ago
            comparator = match[1] == '>' ? '<' : '>'
            { atheletes: where(["birthdate #{comparator} ?", birthdate]) }
        end
    end

    def self.search_by_experience(years_of_experience)
        unless years_of_experience =~ /^\d+$/
            return { error: "Invalid Query (correct examples: 6, 2, 11)" }
        end
        years_of_experience = years_of_experience.to_i
        first_championship_date = years_of_experience.years.ago
        { atheletes: joins(:atheletes_championships)
                    .select('atheletes.* , MIN(atheletes_championships.grant_date) AS least_grant_date')
                    .group('atheletes.id').having('MIN(atheletes_championships.grant_date) <= ?', first_championship_date) }
    end

end

app/controllers/atheletes_controller.rb
class AtheletesController < ApplicationController
  before_action :set_athelete, only: [:show, :edit, :update, :destroy]

  # GET /atheletes
  # GET /atheletes.json
  def index
    @atheletes = Athelete.all
  end

  # GET /atheletes/1
  # GET /atheletes/1.json
  def show
  end

  # GET /atheletes/new
  def new
    @athelete = Athelete.new
  end

  # GET /atheletes/1/edit
  def edit
  end

  # POST /atheletes
  # POST /atheletes.json
  def create
    @athelete = Athelete.new(athelete_params)

    respond_to do |format|
      if @athelete.save
        format.html { redirect_to @athelete, notice: 'Athelete was successfully created.' }
        format.json { render :show, status: :created, location: @athelete }
      else
        format.html { render :new }
        format.json { render json: @athelete.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /atheletes/1
  # PATCH/PUT /atheletes/1.json
  def update
    respond_to do |format|
      if @athelete.update(athelete_params)
        format.html { redirect_to @athelete, notice: 'Athelete was successfully updated.' }
        format.json { render :show, status: :ok, location: @athelete }
      else
        format.html { render :edit }
        format.json { render json: @athelete.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /atheletes/1
  # DELETE /atheletes/1.json
  def destroy
    @athelete.destroy
    respond_to do |format|
      format.html { redirect_to atheletes_url, notice: 'Athelete was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_athelete
      @athelete = Athelete.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def athelete_params
      params.require(:athelete).permit(:name, :birthdate, skill_ids: [], championship_ids: [])
    end
end

app/helpers/atheletes_helper.rb
module AtheletesHelper
end

app/views/atheletes/_athelete.html.erb
<tr>
    <td><%= athelete.name %></td>
    <td><%= athelete.birthdate %></td>
    <td><%= athelete.skills.map{|skill| skill.name} %>
    <td><%= athelete.atheletes_championships.map{|ac| ac.championship.name + (ac.grant_date ? (" " + ac.grant_date.year.to_s) : "") } %>
</tr>

app/views/atheletes/_form.html.erb
<%= form_with(model: athelete, local: true) do |form| %>
  <% if athelete.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(athelete.errors.count, "error") %> prohibited this athelete from being saved:</h2>

      <ul>
        <% athelete.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :birthdate %>
    <%= form.date_select :birthdate, :start_year=>1900,:end_year=>2021 %>
  </div>

  <div class="field">
    <%= form.label :skill_ids %>
    <%= form.select :skill_ids, options_from_collection_for_select(Skill.order(:name), :id, :name), {}, {:multiple => true, :size => 4} %>
  </div>

  <div class="field">
    <%= form.label :championship_ids %>
    <%= form.select :championship_ids, options_from_collection_for_select(Championship.order(:name), :id, :name), {}, {:multiple => true, :size => 4} %>
  </div>
   
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/atheletes/edit.html.erb
<h1>Editing Athelete</h1>

<%= render 'form', athelete: @athelete %>

<%= link_to 'Show', @athelete %> |
<%= link_to 'Back', atheletes_path %>

app/views/atheletes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Atheletes</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Birthdate</th>
      <th>Skills</th>
      <th>Championship</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @atheletes.each do |athelete| %>
      <tr>
        <td><%= athelete.name %></td>
        <td><%= athelete.birthdate %></td>
        <td><%= athelete.skills.map{|skill| skill.name} %>
        <td><%= athelete.atheletes_championships.map{|ac| ac.championship.name + (ac.grant_date ? (" " + ac.grant_date.year.to_s) : "") } %>
        <td><%= link_to 'Show', athelete %></td>
        <td><%= link_to 'Edit', edit_athelete_path(athelete) %></td>
        <td><%= link_to 'Destroy', athelete, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Athelete', new_athelete_path %>

app/views/atheletes/new.html.erb
<h1>New Athelete</h1>

<%= render 'form', athelete: @athelete %>

<%= link_to 'Back', atheletes_path %>

app/views/atheletes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @athelete.name %>
</p>

<p>
  <strong>Birthdate:</strong>
  <%= @athelete.birthdate %>
</p>

<p>
  <strong>Skills:</strong>
  <%= @athelete.skills.map{|skill| skill.name} %>
</p>

<p>
  <strong>Championships:</strong>
  <%= @athelete.atheletes_championships.map{|ac| ac.championship.name + (ac.grant_date ? (" " + ac.grant_date.year.to_s) : "") } %>
</p>

<%= link_to 'Edit', edit_athelete_path(@athelete) %> |
<%= link_to 'Back', atheletes_path %>