config/routes.rb
Rails.application.routes.draw do
  get :search, 'search/index'
  root 'static_pages#home'
  resources :atheletes
  resources :championships
  resources :skills
  resources :atheletes_championships
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/atheletes_championship.rb
class AtheletesChampionship < ApplicationRecord
  belongs_to :athelete
  belongs_to :championship
end

app/controllers/atheletes_championships_controller.rb
class AtheletesChampionshipsController < ApplicationController
  before_action :set_atheletes_championship, only: [:show, :edit, :update, :destroy]

  # GET /atheletes_championships
  # GET /atheletes_championships.json
  def index
    @atheletes_championships = AtheletesChampionship.all
  end

  # GET /atheletes_championships/1
  # GET /atheletes_championships/1.json
  def show
  end

  # GET /atheletes_championships/new
  def new
    @atheletes_championship = AtheletesChampionship.new
  end

  # GET /atheletes_championships/1/edit
  def edit
  end

  # POST /atheletes_championships
  # POST /atheletes_championships.json
  def create
    @atheletes_championship = AtheletesChampionship.new(atheletes_championship_params)

    respond_to do |format|
      if @atheletes_championship.save
        format.html { redirect_to @atheletes_championship, notice: 'Atheletes championship was successfully created.' }
        format.json { render :show, status: :created, location: @atheletes_championship }
      else
        format.html { render :new }
        format.json { render json: @atheletes_championship.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /atheletes_championships/1
  # PATCH/PUT /atheletes_championships/1.json
  def update
    respond_to do |format|
      if @atheletes_championship.update(atheletes_championship_params)
        format.html { redirect_to @atheletes_championship, notice: 'Atheletes championship was successfully updated.' }
        format.json { render :show, status: :ok, location: @atheletes_championship }
      else
        format.html { render :edit }
        format.json { render json: @atheletes_championship.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /atheletes_championships/1
  # DELETE /atheletes_championships/1.json
  def destroy
    @atheletes_championship.destroy
    respond_to do |format|
      format.html { redirect_to atheletes_championships_url, notice: 'Atheletes championship was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_atheletes_championship
      @atheletes_championship = AtheletesChampionship.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def atheletes_championship_params
      params.require(:atheletes_championship).permit(:athelete_id, :championship_id, :grant_date)
    end
end

app/helpers/atheletes_championships_helper.rb
module AtheletesChampionshipsHelper
end

app/views/atheletes_championships/_form.html.erb
<%= form_with(model: atheletes_championship, local: true) do |form| %>
  <% if atheletes_championship.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(atheletes_championship.errors.count, "error") %> prohibited this atheletes_championship from being saved:</h2>

      <ul>
        <% atheletes_championship.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :athelete_id %>
    <%= form.select :athelete_id, options_from_collection_for_select(Athelete.order(:name), :id, :name), {}, {:multiple => false, :size => 4} %>
  </div>

  <div class="field">
    <%= form.label :championship_id %>
    <%= form.select :championship_id, options_from_collection_for_select(Championship.order(:name), :id, :name), {}, {:multiple => false, :size => 4} %>
  </div>

  <div class="field">
    <%= form.label :grant_date %>
    <%= form.date_select :grant_date, start_year: 1900, end_year: 2021 %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/atheletes_championships/edit.html.erb
<h1>Editing Atheletes Championship</h1>

<%= render 'form', atheletes_championship: @atheletes_championship %>

<%= link_to 'Show', @atheletes_championship %> |
<%= link_to 'Back', atheletes_championships_path %>

app/views/atheletes_championships/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Atheletes Championships</h1>

<table>
  <thead>
    <tr>
      <th>Athelete</th>
      <th>Championship</th>
      <th>Grant date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @atheletes_championships.each do |atheletes_championship| %>
      <tr>
        <td><%= atheletes_championship.athelete.name %></td>
        <td><%= atheletes_championship.championship.name %></td>
        <td><%= atheletes_championship.grant_date %></td>
        <td><%= link_to 'Show', atheletes_championship %></td>
        <td><%= link_to 'Edit', edit_atheletes_championship_path(atheletes_championship) %></td>
        <td><%= link_to 'Destroy', atheletes_championship, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Atheletes Championship', new_atheletes_championship_path %>

app/views/atheletes_championships/new.html.erb
<h1>New Atheletes Championship</h1>

<%= render 'form', atheletes_championship: @atheletes_championship %>

<%= link_to 'Back', atheletes_championships_path %>

app/views/atheletes_championships/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Athelete:</strong>
  <%= @atheletes_championship.athelete_id %>
</p>

<p>
  <strong>Championship:</strong>
  <%= @atheletes_championship.championship_id %>
</p>

<p>
  <strong>Grant date:</strong>
  <%= @atheletes_championship.grant_date %>
</p>

<%= link_to 'Edit', edit_atheletes_championship_path(@atheletes_championship) %> |
<%= link_to 'Back', atheletes_championships_path %>